version: "3.12"

services:
  67d87764b776fd6a329eccc3_service:
    image: 67d87764b776fd6a329eccc3_streamlit_app
    container_name: 67d87764b776fd6a329eccc3_container
    # Adjust your desired external port mapping here. For example:
    # "8502:8501" means the app is internally on 8501, but externally accessible on 8502.
    ports:
      - "8501:8501"
    environment:
      - PORT=8501  # This must match the internal port used by Streamlit
      - LAB_ID=67d87764b776fd6a329eccc3
    restart: always
