
name: Build and Push to Docker Hub

on:
  push:
    tags:
      - "v*.*.*"
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t qunikamshreyas/67d87764b776fd6a329eccc3_streamlit_app .
          # e.g., docker build -t your-username/streamlit-app:latest .

      - name: Push Docker image
        run: |
          docker push qunikamshreyas/67d87764b776fd6a329eccc3_streamlit_app
          # e.g., docker push your-username/streamlit-app:latest
